apiVersion: apps/v1
kind: Deployment
metadata:
  name: formatter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formatter
  template:
    metadata:
      labels:
        app: formatter
    spec:
      containers:
        - name: app
          image: mr/formatter:1.0
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: formatter
spec:
  selector:
    app: formatter
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer